# Use "gomake install" to build and install this package.
include $(GOROOT)/src/Make.inc

TARG=github.com/hanwen/go-fuse/rpcfs
DEPS=../fuse

GOFILES=fsserver.go \
	rpcfs.go \

include $(GOROOT)/src/Make.pkg

