# Use "gomake install" to build and install this package.
include $(GOROOT)/src/Make.inc

TARG=github.com/hanwen/termite/attr
DEPS=../../go-fuse/fuse

GOFILES=attrcache.go \
	fileset.go \
	filesetwaiter.go \
	fileattr.go \
	misc.go

include $(GOROOT)/src/Make.pkg

