# Use "gomake install" to build and install this package.
include $(GOROOT)/src/Make.inc

TARG=github.com/hanwen/termite/splice

GOFILES=splice.go \
	copy.go \
	pool.go

include $(GOROOT)/src/Make.pkg

