# Use "gomake install" to build and install this package.
include $(GOROOT)/src/Make.inc

TARG=github.com/hanwen/termite/stats

GOFILES=periodicsampler.go \
	cpustat.go \
	timerpc.go \
	serverstats.go \

include $(GOROOT)/src/Make.pkg

